sudo: false
dist: trusty

language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

git:
    depth: 1

env:
    global:
        - CC="ccache gcc"
        - PHALCON_VERSION=v3.3.1

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.2
        - php: nightly

cache:
    # See: https://github.com/travis-ci/travis-ci/issues/8714
    edge: true
    apt: true
    ccache: true
    timeout: 604800
    directories:
        - $HOME/.ccache
        - $HOME/.composer/cache
        - $HOME/pear
        - $HOME/.local/lib

before_install:
    - ulimit -c unlimited -S || true
    - phpenv config-rm xdebug.ini || true
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com $GH_TOKEN; fi;

install:
    - bash $TRAVIS_BUILD_DIR/tests/ci/install_phalcon.sh
    - echo 'extension=memcached.so' > $(phpenv root)/versions/$(phpenv version-name)/etc/conf.d/50-memcached.ini
    - travis_retry composer install --prefer-dist --no-interaction --no-suggest --optimize-autoloader
    - ls -al `$(phpenv which php-config) --extension-dir`
    - $(phpenv which php) -v
    - $(phpenv which php) -m
    - echo 'SHOW VARIABLES LIKE "%version%"' | mysql -u root

before_script:
    - echo 'CREATE DATABASE phosphorum CHARSET=utf8 COLLATE=utf8_unicode_ci' | mysql -u root
    - echo "CREATE USER 'phosphorum'@'%' IDENTIFIED BY 'secret'" | mysql -u root
    - echo "GRANT ALL PRIVILEGES ON phosphorum.* TO 'phosphorum'@'%' WITH GRANT OPTION" | mysql -u root
    - cat schemas/forum.sql | mysql -u root phosphorum
    - cp ./tests/.env.travis .env
    - php -S 127.0.0.1:8000 -t public/ .htrouter.php >/dev/null 2>&1 &

script:
    - vendor/bin/phpcs
    - vendor/bin/codecept build
    - vendor/bin/codecept run unit
    - vendor/bin/codecept run console
    - vendor/bin/codecept run functional
    - vendor/bin/codecept run acceptance

after_failure:
    - for file in `ls ./tests/_output`; do [ -f ./tests/_output/$file ] && cat ./tests/_output/$file; done;

notifications:
    email:
        on_success: never
        on_failure: never

addons:
    apt:
        packages:
            - beanstalkd
    hosts:
        - db
        - pforum.loc
