language: php

sudo: required
dist: precise

php:
  - 5.5
  - 5.6
  - 7.0

git:
  depth: 1

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    - vendor
    - $HOME/.ccache
    - $HOME/.composer/cache

services:
  - memcached

env:
  global:
    - ZEND_DONT_UNLOAD_MODULES=1 CC="ccache gcc" PATH="$PATH:~/bin" DISPLAY=":99.0"
  matrix:
    - PHALCON_VERSION="3.0.x"
    - PHALCON_VERSION="v3.0.0"

before_install:
  - phpenv config-rm xdebug.ini || true
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer self-update -q
  - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - sh -e /etc/init.d/xvfb start
  - wget -q http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar -O selenium.jar
  - java -jar selenium.jar -port 4444 >/dev/null 2>&1 &

install:
  - (cd cphalcon/build; bash install &>/dev/null)
  - phpenv config-add ./tests/_ci/phalcon.ini &> /dev/null
  - php --ri phalcon
  - cp ./app/config/config.example.php ./app/config/config.php
  - cp ./app/config/development.example.php ./app/config/development.php
  - echo "APP_ENV=testing" > ./.env
  - mysql -e 'CREATE DATABASE phosphorum CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;'
  - cat schemas/forum.sql | mysql phosphorum
  - php ./scripts/random-entries.php >/dev/null 2>&1 &
  - php -S 127.0.0.1:8000 -t public/ .htrouter.php >/dev/null 2>&1 &
  - sleep 5

script:
  - ./bin/phpcs --ignore=app/cache/*,app/config/*,vendor/ -s app/
  - ./bin/codecept run unit
  - ./bin/codecept run -vvv functional
  - ./bin/codecept run acceptance

notifications:
  email:
    recipients:
      - build@phalconphp.com
    on_success: change
    on_failure: always

addons:
  apt:
    packages:
      - gdb
      - re2c
